### ISSUE TITLE
Actividad  6 hilos infografia Erik Cuevas 

### ISSUE THREAD

**Issue by ErikCuevas03** [SistemasTecTlaxiaco/infografia-de-hilos-ErikCuevas03#2]
[HILOS (2).pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-ErikCuevas03/files/15102009/HILOS.2.pdf)

**Comment by IrvinSanchez-dev** [comment]
Dado a la rubrica de evaluación obtuviste un 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
